fixtures:
  forge_modules:
    stdlib:
      repo: puppetlabs/stdlib
    mysql:
      repo: puppetlabs/mysql
    postgresql:
      repo: puppetlabs/postgresql
    java:
      repo: puppetlabs/java
    java_ks:
      repo: puppetlabs/java_ks
    # Dependency of other modules
    concat:
      repo: puppetlabs/concat
    archive:
      repo: puppet/archive
    systemd:
      repo: puppet/systemd
  symlinks:
    keycloak: "#{source_dir}"
