fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.25.0
    mysql:
      repo: https://github.com/puppetlabs/puppetlabs-mysql.git
      ref: v10.3.0
    postgresql:
      repo: https://github.com/puppetlabs/puppetlabs-postgresql.git
      ref: v6.6.0
    java:
      repo: https://github.com/puppetlabs/puppetlabs-java.git
      ref: v6.3.0
    java_ks:
      repo: https://github.com/puppetlabs/puppetlabs-java_ks.git
      ref: 1.4.1
    archive:
      repo: https://github.com/voxpupuli/puppet-archive.git
      ref: v0.5.1
    systemd:
      repo: https://github.com/voxpupuli/puppet-systemd.git
      ref: 0.4.0
    augeas_core:
      repo: https://github.com/puppetlabs/puppetlabs-augeas_core.git
      ref: 1.1.1
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      ref: 1.0.7
    apt:
      repo: https://github.com/puppetlabs/puppetlabs-apt.git
    concat:
      repo: https://github.com/puppetlabs/puppetlabs-concat.git
  symlinks:
    keycloak: "#{source_dir}"
