---
.github/workflows/ci.yaml:
  unit_name: Puppet ${{ matrix.puppet }} (Ruby ${{ matrix.ruby }} fixtures=${{ matrix.fixtures }})
  unit_includes:
    - ruby: '2.5.7'
      puppet: '6'
      fixtures: .fixtures-latest.yml
      allow_failure: true
    - ruby: '2.7.0'
      puppet: '7'
      fixtures: .fixtures-latest.yml
      allow_failure: true
  acceptance_name: '${{ matrix.puppet }} ${{ matrix.set }} (keycloak=${{ matrix.keycloak_version }} full=${{ matrix.keycloak_full }})'
  acceptance_matrix:
    set:
      - centos-7
      - rocky-8
      - debian-9
      - debian-10
      - ubuntu-1804
      - ubuntu-2004
    puppet:
      - puppet6
      - puppet7
    keycloak_version:
      - '12.0.4'
      - '13.0.1'
      - '14.0.0'
      - '15.0.1'
      - '16.1.1'
    keycloak_full: ['no']
    keycloak_domain_mode_cluster: ['no']
  acceptance_includes:
    - set: centos-7
      puppet: puppet6
      keycloak_version: 12.0.4
      keycloak_full: 'yes'
    - set: centos-7
      puppet: puppet7
      keycloak_version: 12.0.4
      keycloak_full: 'yes'
    - set: centos-7
      puppet: puppet7
      keycloak_version: 13.0.1
      keycloak_full: 'yes'
    - set: centos-7
      puppet: puppet7
      keycloak_version: 14.0.0
      keycloak_full: 'yes'
    - set: centos-7
      puppet: puppet7
      keycloak_version: 15.0.1
      keycloak_full: 'yes'
    - set: centos-7
      puppet: puppet7
      keycloak_version: 16.1.1
      keycloak_full: 'yes'
    - set: centos-7-domain-mode-cluster
      puppet: puppet7
      keycloak_version: 12.0.4
      keycloak_domain_mode_cluster: 'yes'
    - set: centos-7-domain-mode-cluster
      puppet: puppet7
      keycloak_version: 13.0.1
      keycloak_domain_mode_cluster: 'yes'
    - set: centos-7-domain-mode-cluster
      puppet: puppet7
      keycloak_version: 14.0.0
      keycloak_domain_mode_cluster: 'yes'
    - set: centos-7-domain-mode-cluster
      puppet: puppet7
      keycloak_version: 15.0.1
      keycloak_domain_mode_cluster: 'yes'
    - set: centos-7-domain-mode-cluster
      puppet: puppet7
      keycloak_version: 16.1.1
      keycloak_domain_mode_cluster: 'yes'
.gitignore:
  paths:
    - /vagrant/.vagrant/
    - /vagrant/*.log
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/debian-10.yml:
  packages:
    - iproute2
spec/acceptance/nodesets/ubuntu-1804.yml:
  packages:
    - iproute2
spec/acceptance/nodesets/ubuntu-2004.yml:
  packages:
    - iproute2
