#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-stdlib'
mod 'puppetfinland-easy_ipa',
  :git => 'https://github.com/Puppet-Finland/puppet-ipa.git',
  :commit => '67874ab7f40e4643b77adfd4155f9eb494776bc8'
mod 'puppetlabs-mysql'
mod 'puppetlabs-java'
mod 'puppetlabs-java_ks'
mod 'puppet-archive'
mod 'camptocamp-systemd'
mod 'puppetlabs-concat'
mod 'puppetlabs-apt'
mod 'puppetlabs-postgresql'
mod 'puppetlabs-cron_core'
mod 'puppetlabs-inifile'
mod 'puppetlabs-k5login_core'
mod 'puppetlabs-resource_api'
mod 'puppetlabs-translate'
mod 'puppetlabs-puppetserver_gem'
mod 'puppetlabs-haproxy'
